### ISSUE TITLE
"wp core is-installed query" hanging

### ISSUE THREAD

**Issue by juditnovak** [canonical/wordpress-k8s-operator#168]
### Bug Description

After relating the `wordpress-k8s` charm to an existing `mysql-k8s` + `mysql-router-k8s` pair,  it keeps hainging with the following error repeting in `juju debug-log`

```
ops.pebble.ChangeError: cannot perform the following tasks:
- exec command "wp" (timed out after 1m0s: context deadline exceeded)
----- Logs from task 0 -----
2023-11-21T20:39:36Z ERROR timed out after 1m0s: context deadline exceeded
-----
```

### To Reproduce

juju deploy wordpress-k8s --channel latest/edge

juju deploy mysql-router-k8s --trust --channel 8.0/edge
juju deploy mysql-k8s --trust --channel 8.0/edge

juju relate mysql-router-k8s mysql-k8s
juju relate mysql-router-k8s wordpress-k8s

### Environment

juju 3.1/stable (i.e. 3.1.6)

### Relevant log output

```shell
unit-wordpress-k8s-0: 21:18:42 ERROR unit.wordpress-k8s/0.juju-log database:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/./src/charm.py", line 1477, in <module>
    main(WordpressCharm)
  File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/framework.py", line 340, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/framework.py", line 842, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 1958, in _on_relation_changed_event
    getattr(self.on, "database_created").emit(
  File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/framework.py", line 340, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/framework.py", line 842, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/./src/charm.py", line 1445, in _reconciliation
    self._core_reconciliation()
  File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/./src/charm.py", line 811, in _core_reconciliation
    self._start_server()
  File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/./src/charm.py", line 725, in _start_server
    if not self._wp_is_installed():
  File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/./src/charm.py", line 573, in _wp_is_installed
    return self._run_wp_cli(["wp", "core", "is-installed"]).return_code == 0
  File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/./src/charm.py", line 526, in _run_wp_cli
    result = self._run_cli(
  File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/./src/charm.py", line 486, in _run_cli
    stdout, stderr = process.wait_output()
  File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/pebble.py", line 1369, in wait_output
    exit_code: int = self._wait()
  File "/var/lib/juju/agents/unit-wordpress-k8s-0/charm/venv/ops/pebble.py", line 1330, in _wait
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- exec command "wp" (timed out after 1m0s: context deadline exceeded)
----- Logs from task 0 -----
```
### Additional context
wordpress-k8s is stuck in `blocked: Waiting for db relation/config" state`

```
Model  Controller          Cloud/Region        Version  SLA          Timestamp
wp4    microk8s-localhost  microk8s/localhost  3.1.6    unsupported  22:04:15+01:00

App               Version                  Status   Scale  Charm             Channel      Rev  Address         Exposed  Message
mysql-k8s         8.0.34-0ubuntu0.22.04.1  active       1  mysql-k8s         8.0/edge     110  10.152.183.228  no       
mysql-router-k8s  8.0.34-0ubuntu0.22.04.1  active       1  mysql-router-k8s  8.0/edge      77  10.152.183.210  no       
wordpress-k8s     6.4.1                    waiting      1  wordpress-k8s     latest/edge   66  10.152.183.70   no       installing agent

Unit                 Workload  Agent      Address       Ports  Message
mysql-k8s/0*         active    idle       10.1.244.113         Primary
mysql-router-k8s/0*  active    idle       10.1.244.74          
wordpress-k8s/0*     blocked   executing  10.1.244.108         Waiting for db relation/config

Integration provider                 Requirer                             Interface           Type     Message
mysql-k8s:database                   mysql-router-k8s:backend-database    mysql_client        regular  
mysql-k8s:database-peers             mysql-k8s:database-peers             mysql_peers         peer     
mysql-k8s:restart                    mysql-k8s:restart                    rolling_op          peer     
mysql-k8s:upgrade                    mysql-k8s:upgrade                    upgrade             peer     
mysql-router-k8s:database            wordpress-k8s:database               mysql_client        regular  
mysql-router-k8s:mysql-router-peers  mysql-router-k8s:mysql-router-peers  mysql_router_peers  peer     
mysql-router-k8s:upgrade-version-a   mysql-router-k8s:upgrade-version-a   upgrade             peer     
wordpress-k8s:wordpress-replica      wordpress-k8s:wordpress-replica      wordpress-replica   peer    
```

**Comment by weiiwang01** [comment]
Thanks @juditnovak ! I will take a look at this problem.

**Comment by weiiwang01** [comment]
Hi @juditnovak I've identified the root cause of our recent issue: it caused by the MySQL server requiring a TLS connection, which our current WordPress setup doesn't support.

I can fix this issue by manually added `define('MYSQL_CLIENT_FLAGS', MYSQLI_CLIENT_SSL);` to the WordPress configuration file. Could you advise if there's a method to check if the database server requires TLS connection? This will allow me to update the charm to dynamically add this configuration when necessary.

**Comment by weiiwang01** [comment]
> > Hi @juditnovak I've identified the root cause of our recent issue: it caused by the MySQL server requiring a TLS connection, which our current WordPress setup doesn't support.
> > I can fix this issue by manually added `define('MYSQL_CLIENT_FLAGS', MYSQLI_CLIENT_SSL);` to the WordPress configuration file. Could you advise if there's a method to check if the database server requires TLS connection? This will allow me to update the charm to dynamically add this configuration when necessary.
> 
> Sorry, actually that's not true, although adding `define('MYSQL_CLIENT_FLAGS', MYSQLI_CLIENT_SSL);` fixed this issue, I can connect to the mysql database without SSL using other client like Python mysql connector. The true problem behind this is still unknown.

Can confirm that this doesn't happen when directly connecting to the `mysql-k8s` charm without `mysql-router-k8s`.

**Comment by weiiwang01** [comment]
I have compared the packet capture of the two situation of with and without the `mysql-router-k8s` and it seems like with `mysql-router-k8s`, the `fast_auth_success` or `perform_full_authentication` packets of the `caching_sha2_password` authentication process is never send to WordPress. This is probably the reason why WordPress hangs during the database connection, the authentication process is never finished to WordPress.

**Comment by weiiwang01** [comment]
> I have compared the packet capture of the two situation of with and without the `mysql-router-k8s` and it seems like with `mysql-router-k8s`, the `fast_auth_success` or `perform_full_authentication` packets of the `caching_sha2_password` authentication process is never send to WordPress. This is probably the reason why WordPress hangs during the database connection, the authentication process is never finished to WordPress.

This is probably a mysql client compatibility issues, as some other client like Python client can finish the handshake/authentication process with only the ok response.

**Comment by weiiwang01** [comment]
Possibly related: https://bugs.launchpad.net/charm-mysql-router/+bug/2040018

**Comment by taurus-forever** [comment]
> Possibly related: https://bugs.launchpad.net/charm-mysql-router/+bug/2040018

The provided link is for: `legacy` VM charm from OpenStack team ([this one](https://charmhub.io/mysql-router?channel=8.0/stable)).
This bugreport is for Data team K8s charm ([this one](https://charmhub.io/mysql-router-k8s?channel=8.0/stable)).

@carlcsaposs-canonical can you please help @weiiwang01 here. Tnx!

P.S. MySQL server supports and offer TLS by default (without relation with tls-certificatates charm), it is a built-in feature.

There were major changes in [mysql-router 8.0.33](https://dev.mysql.com/doc/relnotes/mysql-router/8.0/en/news-8-0-33.html) (to reuse TLS connection from server...) maybe we have some issue here to report.

Possible options: try with mysql-router 8.0.35 or 8.2 (see [this](https://dev.mysql.com/doc/relnotes/mysql-router/8.0/en/news-8-0-35.html)):
```
Authentication failed for third-party clients using non-SSL connections, with caching-sha2-password and the following SSL options configured:

client_ssl_mode set to PREFERRED or PASSTHROUGH

server_ssl_mode=AS_CLIENT

An error similar to the following was returned:

        Couldn't read RSA public key from server
(Bug #35737521)
```

**Comment by taurus-forever** [comment]
The issue in mysql-router 8.0.34, the fix from 8.0.35 works well:

```
> juju add-model test65
Added 'test65' model on microk8s/localhost with credential 'microk8s' for user 'admin'
> juju deploy mysql-k8s --trust --channel 8.0/edge
Located charm "mysql-k8s" in charm-hub, revision 110
Deploying "mysql-k8s" from charm-hub charm "mysql-k8s", revision 110 in channel 8.0/edge on ubuntu@22.04/stable
> juju deploy mysql-router-k8s --trust --channel 8.0/edge
Located charm "mysql-router-k8s" in charm-hub, revision 77
Deploying "mysql-router-k8s" from charm-hub charm "mysql-router-k8s", revision 77 in channel 8.0/edge on ubuntu@22.04/stable
> juju deploy wordpress-k8s --channel latest/edge
Located charm "wordpress-k8s" in charm-hub, revision 67
Deploying "wordpress-k8s" from charm-hub charm "wordpress-k8s", revision 67 in channel latest/edge on ubuntu@22.04/stable
> juju relate mysql-k8s mysql-router-k8s


# wait for deployments...

ubuntu@juju3:~$ juju status --relations
Model   Controller  Cloud/Region        Version  SLA          Timestamp
test65  microk8s    microk8s/localhost  3.1.6    unsupported  13:26:20+01:00

App               Version                  Status   Scale  Charm             Channel      Rev  Address         Exposed  Message
mysql-k8s         8.0.34-0ubuntu0.22.04.1  active       1  mysql-k8s         8.0/edge     110  10.152.183.229  no       
mysql-router-k8s  8.0.34-0ubuntu0.22.04.1  blocked      1  mysql-router-k8s  8.0/edge      77  10.152.183.146  no       Missing relation: database
wordpress-k8s     6.4.1                    waiting      1  wordpress-k8s     latest/edge   67  10.152.183.204  no       installing agent

Unit                 Workload  Agent  Address       Ports  Message
mysql-k8s/0*         active    idle   10.1.141.233         Primary
mysql-router-k8s/0*  active    idle   10.1.141.211         
wordpress-k8s/0*     blocked   idle   10.1.141.199         Waiting for db relation/config

Integration provider                 Requirer                             Interface           Type     Message
mysql-k8s:database                   mysql-router-k8s:backend-database    mysql_client        regular  
mysql-k8s:database-peers             mysql-k8s:database-peers             mysql_peers         peer     
mysql-k8s:restart                    mysql-k8s:restart                    rolling_op          peer     
mysql-k8s:upgrade                    mysql-k8s:upgrade                    upgrade             peer     
mysql-router-k8s:mysql-router-peers  mysql-router-k8s:mysql-router-peers  mysql_router_peers  peer     
mysql-router-k8s:upgrade-version-a   mysql-router-k8s:upgrade-version-a   upgrade             peer     
wordpress-k8s:wordpress-replica      wordpress-k8s:wordpress-replica      wordpress-replica   peer     
ubuntu@juju3:~$ 


> juju ssh --container mysql-router mysql-router-k8s/0 bash

root@mysql-router-k8s-0:/# mysqlrouter --version
MySQL Router  Ver 8.0.34-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))

root@mysql-router-k8s-0:/# apt update 
...
root@mysql-router-k8s-0:/# apt install mysql-router
...

root@mysql-router-k8s-0:/# mysqlrouter --version
MySQL Router  Ver 8.0.35-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))


root@mysql-router-k8s-0:/# /charm/bin/pebble stop mysql_router
root@mysql-router-k8s-0:/# ps auxww | grep mysqlrouter
root         381  0.0  0.0   3468  1552 pts/0    S+   12:27   0:00 grep --color=auto mysqlrouter
root@mysql-router-k8s-0:/# /charm/bin/pebble start mysql_router
root@mysql-router-k8s-0:/# ps auxww | grep mysqlrouter
mysql        390  7.0  0.0 1845476 21980 ?       Sl   12:27   0:00 mysqlrouter --config /etc/mysqlrouter/mysqlrouter.conf


> juju relate mysql-router-k8s wordpress-k8s
> juju status

ubuntu@juju3:~$ juju status
Model   Controller  Cloud/Region        Version  SLA          Timestamp
test65  microk8s    microk8s/localhost  3.1.6    unsupported  13:29:31+01:00

App               Version                  Status  Scale  Charm             Channel      Rev  Address         Exposed  Message
mysql-k8s         8.0.34-0ubuntu0.22.04.1  active      1  mysql-k8s         8.0/edge     110  10.152.183.229  no       
mysql-router-k8s  8.0.34-0ubuntu0.22.04.1  active      1  mysql-router-k8s  8.0/edge      77  10.152.183.146  no       
wordpress-k8s     6.4.1                    active      1  wordpress-k8s     latest/edge   67  10.152.183.204  no       

Unit                 Workload  Agent  Address       Ports  Message
mysql-k8s/0*         active    idle   10.1.141.233         Primary
mysql-router-k8s/0*  active    idle   10.1.141.211         
wordpress-k8s/0*     active    idle   10.1.141.199         
ubuntu@juju3:~$ 


```

**Comment by taurus-forever** [comment]
@weiiwang01 for the history, 8.0.34 release to stable on January 3: https://charmhub.io/mysql-router-k8s/docs/r-releases-rev82
The ticket can be resolved.

**Comment by weiiwang01** [comment]
> @weiiwang01 for the history, 8.0.34 release to stable on January 3: https://charmhub.io/mysql-router-k8s/docs/r-releases-rev82 The ticket can be resolved.

Thank you, issue closed.
